# 1. Import TensorFlow

In [ ]:
import tensorflow as tf


# 2. Create Tensors

In [ ]:
# Create a constant tensor
tensor_const = tf.constant([1, 2, 3])

# Create a variable tensor
tensor_var = tf.Variable([4, 5, 6])

# Create a placeholder (for input data)
tensor_placeholder = tf.placeholder(tf.float32, shape=(None, 3))


# 3. Basic Operations

In [ ]:
# Element-wise addition
result_add = tensor_const + tensor_var

# Element-wise multiplication
result_mul = tf.multiply(tensor_const, tensor_var)

# Matrix multiplication
result_matmul = tf.matmul(tensor_const, tf.transpose(tensor_var))


# 4. Session (Eager Execution)

In [ ]:
# Enable eager execution (not required in TensorFlow 2.x by default)
tf.config.run_functions_eagerly(True)

# Run operations eagerly
result = result_add.numpy()
print(result)


# 5. Gradient Tape (for Automatic Differentiation)

In [ ]:
# Example of automatic differentiation using GradientTape
with tf.GradientTape() as tape:
    tape.watch(tensor_var)
    result = tf.reduce_sum(tf.square(tensor_var))

# Calculate gradient
gradient = tape.gradient(result, tensor_var)
print(gradient.numpy())


# 6. Custom Operations

In [ ]:
# Define a custom operation
@tf.function
def custom_operation(x):
    return tf.square(x) + 3 * x + 2

# Use the custom operation
result_custom = custom_operation(tensor_var)
print(result_custom.numpy())


# 7. Optimizers and Training Loop

In [ ]:
# Define an optimizer (e.g., Gradient Descent)
optimizer = tf.optimizers.SGD(learning_rate=0.01)

# Training loop example
for _ in range(num_epochs):
    with tf.GradientTape() as tape:
        # Compute loss
        loss = compute_loss()

    # Compute gradients
    gradients = tape.gradient(loss, trainable_variables)

    # Update weights
    optimizer.apply_gradients(zip(gradients, trainable_variables))


# 8. Saving and Restoring Variables

In [ ]:
# Save variables
checkpoint = tf.train.Checkpoint(model=model)
checkpoint.save("model_checkpoint.ckpt")

# Restore variables
checkpoint.restore("model_checkpoint.ckpt")


In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

# Creating Tensors

In [14]:
tensor_const = tf.constant([1, 2, 3]) # One dimension will not work with tf.matmul it must be at least 2 dimension
tensor_var = tf.Variable([4, 5, 6])   # One dimension will not work with tf.matmul it must be at least 2 dimension


In [22]:
tensor_const = tf.constant([[1, 2, 3]]) # 2 dimension or above will work with tf.matmul
tensor_var = tf.Variable([[4, 5, 6]])   # 2 dimension or above will work with tf.matmul

# Basic Operations on Tensors

In [ ]:
# Tensor bitwise addition

In [26]:
result_add = tensor_const + tensor_var 

In [27]:
print(result_add)

tf.Tensor([[5 7 9]], shape=(1, 3), dtype=int32)


In [ ]:
# Tensor bitwise subtraction

In [31]:
result_sub = tensor_const - tensor_var 

In [32]:
print(result_sub)

tf.Tensor([[-3 -3 -3]], shape=(1, 3), dtype=int32)


In [ ]:
# Tensor bitwise division

In [33]:
result_div = tensor_const / tensor_var

In [34]:
print(result_div)

tf.Tensor([[0.25 0.4  0.5 ]], shape=(1, 3), dtype=float64)


In [ ]:
# Tensor bitwise multiplication

In [28]:
result_mul = tf.multiply(tensor_const, tensor_var)

In [29]:
print(result_mul)

tf.Tensor([[ 4 10 18]], shape=(1, 3), dtype=int32)


In [35]:
# Tensor matrix multiplication

In [30]:
result_matmul = tf.matmul(tensor_const, tf.transpose(tensor_var))

In [24]:
print(result_matmul)

tf.Tensor([[32]], shape=(1, 1), dtype=int32)


# Convert NumPy array to Tensor

In [3]:
numpy_array = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
tensor_from_numpy = tf.convert_to_tensor(numpy_array, dtype=tf.float32)

# Convert Pandas DataFrame to Tensor

In [4]:
data = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}
df = pd.DataFrame(data)
tensor_from_dataframe = tf.constant(df.values, dtype=tf.float32)

In [6]:
print(tensor_from_dataframe)

tf.Tensor(
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]], shape=(3, 3), dtype=float32)


# Convert Images to Tensor

In [8]:
from PIL import Image
image_path = 'image.PNG'
image = Image.open(image_path)
image_array = np.array(image)
tensor_from_image = tf.convert_to_tensor(image_array, dtype=tf.float32)

# Generating computational graph to use it later in finding the gradient 

In TensorFlow, the tf.GradientTape is used to compute the gradient of a computation with respect to its input variables. By default, the tf.GradientTape automatically watches any trainable variables, meaning that you don't need to explicitly use watch for variables that are trainable (like variables created with tf.Variable). However, if you are working with constant tensors or non-trainable variables, you need to explicitly specify that you want to watch them using watch.

In [ ]:
x = tf.constant(3.0)

with tf.GradientTape() as g:
  g.watch(x)
  y = x * x


Here, x is a constant tensor, and by default, it is not watched by the gradient tape. However, you want to compute the gradient of y with respect to x. Therefore, you use g.watch(x) to explicitly tell the gradient tape to watch the constant tensor x. This allows TensorFlow to compute the gradient of y with respect to x during the gradient tape's scope.

If x were a trainable variable created with tf.Variable, you wouldn't need to use g.watch(x) because tf.GradientTape automatically watches trainable variables.

In [ ]:
x = tf.Variable(3.0)

with tf.GradientTape() as g:
  y = x * x


In this case, x is a trainable variable, and TensorFlow automatically watches it without the need for explicit watch statement.

# Building Models

In [36]:
import tensorflow as tf

# Some example variables
w0 = tf.Variable(1.0, trainable=True)
w1 = tf.Variable(2.0, trainable=True)
w2 = tf.Variable(3.0, trainable=True)
w3 = tf.Variable(4.0, trainable=True)
w4 = tf.Variable(5.0, trainable=True)

# Example equation using the variables
def equation(w0, w1, w2, w3, w4, x):
    return w0 * x**4 + w1 * x**3 + w2 * x**2 + w3 * x + w4

# Example input
x_input = tf.constant(2.0)

# Use tf.GradientTape to compute gradients
with tf.GradientTape(persistent=True) as tape:
    # Watch the variables
    tape.watch(w0)
    tape.watch(w1)
    tape.watch(w2)
    tape.watch(w3)
    tape.watch(w4)

    # Compute the output of the equation
    y = equation(w0, w1, w2, w3, w4, x_input)

# Compute gradients with respect to each variable
grad_w0 = tape.gradient(y, w0)
grad_w1 = tape.gradient(y, w1)
grad_w2 = tape.gradient(y, w2)
grad_w3 = tape.gradient(y, w3)
grad_w4 = tape.gradient(y, w4)

# Update the variables (you can use any optimizer here)
learning_rate = 0.01
w0.assign_sub(learning_rate * grad_w0)
w1.assign_sub(learning_rate * grad_w1)
w2.assign_sub(learning_rate * grad_w2)
w3.assign_sub(learning_rate * grad_w3)
w4.assign_sub(learning_rate * grad_w4)

# Clean up resources used by the tape
del tape


In [39]:
print('w0=',w0)
print('w1=',w1)
print('w2=',w2)
print('w3=',w3)
print('w4=',w4)

w0= <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.84000003>
w1= <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.92>
w2= <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.96>
w3= <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.98>
w4= <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.99>


In [43]:
import tensorflow as tf

# Define a simple model with trainable variables
class LinearRegressionModel(tf.Module):
    def __init__(self):
        self.w0 = tf.Variable(1.0, trainable=True)
        self.w1 = tf.Variable(2.0, trainable=True)
        self.w2 = tf.Variable(3.0, trainable=True)
        self.w3 = tf.Variable(4.0, trainable=True)
        self.w4 = tf.Variable(5.0, trainable=True)
        self.w5 = tf.Variable(0.5, trainable=True)  # Additional trainable variable
        

    def equation(self, x):
        # Multiple-input linear regression equation
        return self.w0 * x[:, 0] + self.w1 * x[:, 1] + self.w2 * x[:, 2] + self.w3 * x[:, 3] + self.w4 + self.w5 * x[:, 4] 

# Generate some random data for demonstration
np.random.seed(0)
data_points = np.random.rand(100, 6)  # 100 samples, 6 features

# Create input data and labels
x_train = data_points[:, :5]
y_train = 2 * x_train[:, 0] - 3 * x_train[:, 1] + 1.5 * x_train[:, 2] + 4 * x_train[:, 3] + 5 + 0.5 * x_train[:, 4] + np.random.normal(0, 0.1, size=(100,))

# Convert data to TensorFlow tensors
x_train_tensor = tf.constant(x_train, dtype=tf.float32)
y_train_tensor = tf.constant(y_train, dtype=tf.float32)

# Instantiate the model
model = LinearRegressionModel()

# Training parameters
learning_rate = 0.01
num_epochs = 100

# Define the loss function (mean squared error)
def mean_squared_error(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))

# Training loop
for epoch in range(num_epochs):
    with tf.GradientTape() as tape:
        # Compute predictions
        predictions = model.equation(x_train_tensor)

        # Compute the mean squared error
        loss = mean_squared_error(y_train_tensor, predictions)

    # Compute gradients with respect to trainable variables
    gradients = tape.gradient(loss, model.trainable_variables)

    # Update the trainable variables using the gradients and the learning rate
    for var, grad in zip(model.trainable_variables, gradients):
        var.assign_sub(learning_rate * grad)

    # Print the loss every 10 epochs
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch + 1}/{num_epochs}, Loss: {loss.numpy()}")

# Print the final values of the trainable variables
print("Final Trainable Variables:")
for var in model.trainable_variables:
    print(f"{var.name}: {var.numpy()}")


Epoch 10/100, Loss: 5.873963832855225
Epoch 20/100, Loss: 3.4179155826568604
Epoch 30/100, Loss: 2.4156360626220703
Epoch 40/100, Loss: 1.986089825630188
Epoch 50/100, Loss: 1.782915472984314
Epoch 60/100, Loss: 1.6699206829071045
Epoch 70/100, Loss: 1.5935282707214355
Epoch 80/100, Loss: 1.5326367616653442
Epoch 90/100, Loss: 1.4789106845855713
Epoch 100/100, Loss: 1.4290356636047363
Final Trainable Variables:
Variable:0: 0.6443644165992737
Variable:0: 0.6227445006370544
Variable:0: 2.3087642192840576
Variable:0: 3.41403865814209
Variable:0: 3.827744960784912
Variable:0: -0.028387809172272682


In [44]:
import tensorflow as tf

# Define a simple model with trainable variables
class LinearRegressionModel(tf.Module):
    def __init__(self):
        self.w0 = tf.Variable(1.0, trainable=True)
        self.w1 = tf.Variable(2.0, trainable=True)
        self.w2 = tf.Variable(3.0, trainable=True)
        self.w3 = tf.Variable(4.0, trainable=True)
        self.w4 = tf.Variable(5.0, trainable=True)
        self.w5 = tf.Variable(0.5, trainable=True)  # Additional trainable variable
      

    def equation(self, x):
        # Multiple-input linear regression equation
        return self.w0 * x[:, 0] + self.w1 * x[:, 1] + self.w2 * x[:, 2] + self.w3 * x[:, 3] + self.w4 + self.w5 * x[:, 4] 

# Generate some random data for demonstration
np.random.seed(0)
data_points = np.random.rand(100, 6)  # 100 samples, 6 features

# Create input data and labels
x_train = data_points[:, :5]
y_train = 2 * x_train[:, 0] - 3 * x_train[:, 1] + 1.5 * x_train[:, 2] + 4 * x_train[:, 3] + 5 + 0.5 * x_train[:, 4] + np.random.normal(0, 0.1, size=(100,))

# Convert data to TensorFlow tensors
x_train_tensor = tf.constant(x_train, dtype=tf.float32)
y_train_tensor = tf.constant(y_train, dtype=tf.float32)

# Instantiate the model
model = LinearRegressionModel()

# Create an optimizer (Adam optimizer in this case)
optimizer = tf.optimizers.Adam(learning_rate=0.01)

# Training parameters
num_epochs = 100

# Define the loss function (mean squared error)
def mean_squared_error(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))

# Training loop with Adam optimizer
for epoch in range(num_epochs):
    with tf.GradientTape() as tape:
        # Compute predictions
        predictions = model.equation(x_train_tensor)

        # Compute the mean squared error
        loss = mean_squared_error(y_train_tensor, predictions)

    # Compute gradients with respect to trainable variables
    gradients = tape.gradient(loss, model.trainable_variables)

    # Update the trainable variables using the Adam optimizer
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

    # Print the loss every 10 epochs
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch + 1}/{num_epochs}, Loss: {loss.numpy()}")

# Print the final values of the trainable variables
print("Final Trainable Variables:")
for var in model.trainable_variables:
    print(f"{var.name}: {var.numpy()}")


Epoch 10/100, Loss: 9.301063537597656
Epoch 20/100, Loss: 7.546630859375
Epoch 30/100, Loss: 6.092097759246826
Epoch 40/100, Loss: 4.928334712982178
Epoch 50/100, Loss: 4.027708530426025
Epoch 60/100, Loss: 3.352130651473999
Epoch 70/100, Loss: 2.859957218170166
Epoch 80/100, Loss: 2.5107738971710205
Epoch 90/100, Loss: 2.268342971801758
Epoch 100/100, Loss: 2.102170944213867
Final Trainable Variables:
Variable:0: 0.33037829399108887
Variable:0: 1.1997393369674683
Variable:0: 2.2734334468841553
Variable:0: 3.2785892486572266
Variable:0: 4.278080463409424
Variable:0: -0.20118720829486847


In [50]:
import tensorflow as tf

# Define a simple model with trainable variables as a vector
class LinearRegressionModel(tf.Module):
    def __init__(self):
        # Represent the variables as a single vector
        self.weights = tf.Variable([[1.0, 2.0, 3.0, 4.0, 5.0]], trainable=True)

    def equation(self, x):
        # Multiple-input linear regression equation using matrix multiplication
        return tf.reduce_sum(self.weights * x, axis=1)

# Generate some random data for demonstration
np.random.seed(0)
data_points = np.random.rand(100, 6)  # 100 samples, 6 features

# Create input data and labels
x_train = data_points[:, :5]
y_train = 2 * x_train[:, 0] - 3 * x_train[:, 1] + 1.5 * x_train[:, 2] + 4 * x_train[:, 3] + 5 + 0.5 * x_train[:, 4] + np.random.normal(0, 0.1, size=(100,))

# Convert data to TensorFlow tensors
x_train_tensor = tf.constant(x_train, dtype=tf.float32)
y_train_tensor = tf.constant(y_train, dtype=tf.float32)

# Instantiate the model
model = LinearRegressionModel()

# Create an optimizer (Adam optimizer in this case)
optimizer = tf.optimizers.Adam(learning_rate=0.01)

# Training parameters
num_epochs = 100

# Define the loss function (mean squared error)
def mean_squared_error(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))

# Training loop with Adam optimizer
for epoch in range(num_epochs):
    with tf.GradientTape() as tape:
        # Compute predictions
        predictions = model.equation(x_train_tensor)

        # Compute the mean squared error
        loss = mean_squared_error(y_train_tensor, predictions)

    # Compute gradients with respect to trainable variables
    gradients = tape.gradient(loss, [model.weights])

    # Update the trainable variables using the Adam optimizer
    optimizer.apply_gradients(zip(gradients, [model.weights]))

    # Print the loss every 10 epochs
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch + 1}/{num_epochs}, Loss: {loss.numpy()}")

# Print the final values of the trainable variables (weights)
print("Final Trainable Variables (Weights):")
print(model.weights.numpy())


Epoch 10/100, Loss: 4.227802753448486
Epoch 20/100, Loss: 4.03024435043335
Epoch 30/100, Loss: 3.8759665489196777
Epoch 40/100, Loss: 3.742917537689209
Epoch 50/100, Loss: 3.6180503368377686
Epoch 60/100, Loss: 3.499094247817993
Epoch 70/100, Loss: 3.3861138820648193
Epoch 80/100, Loss: 3.2786853313446045
Epoch 90/100, Loss: 3.1765518188476562
Epoch 100/100, Loss: 3.0796473026275635
Final Trainable Variables (Weights):
[[2.0219421 1.1459466 2.888826  3.994519  4.177248 ]]
